### ISSUE TITLE
Compressing file with type="module" that has imports in it

### ISSUE THREAD

**Issue by sanderese** [django-compressor/django-compressor#1142] opened 2022-08-22 13:46 UTC
Hi there,

I'm importing a file called main.js into my template. In this file I import some stuff from mdbootstrap

`import { Tooltip } from "../mdbootstrap/src/mdb/js/free/tooltip";
import { Modal } from "../mdbootstrap/src/mdb/js/free/modal";`

In my template I try to compress it:

```
{% compress js %}
<script src="{% static 'landingpage/main.js' %}" type="module"></script>
{% endcompress %}
```

Since I'm using imports in the main.js file I'm required to use type="module", but that raises the following exception:

`Couldn't find any precompiler in COMPRESS_PRECOMPILERS setting for mimetype 'module'.`

In the readthedocs it says there's no default for COMPRESS_PRECOMPILERS but it does work out of the box for "regular (read no import) javascript.

How should I configure my settings to work with type="module"? Or am I using a wrong approach to begin with?

Any help is appreciated!

**Comment by carltongibson** [comment] 2022-08-22 13:52
Duplicate of #1141 — Please don't post the same thing multiple times.

**Closed by carltongibson** 2022-08-22 13:52 UTC
