### ISSUE TITLE
Lack of information about project structure.

### ISSUE THREAD

**Issue by aktywnitu** [django-compressor/django-compressor#774] opened 2016-06-17 07:47 UTC
Hi guys,
Thanks for great library.
Unfortunately can't use generated source map - paths to them are really crazy, sometimes buggy I think - for example "/static/all/" instead "static_all".

Please tell me if I need keep my scss files in CAHED/css subdirecotry?
[17/Jun/2016 07:25:39] "GET /static/CACHE/**css**/bootstrap/_variables.scss HTTP/1.1" 404 1819

css in path?
I have them in COMPRESS_ROOT of course. So, maby I need create symbolic link? Can't more easier? Please explain me and others how it works.

**Comment by karyon** [comment] 2016-06-18 11:02
hi, unfortunately i'm not sure what the problem is. django compressor shouldn't replace slashes by underscores, it also shouldn't require "css" to be in any path, and it shouldn't require you to create any symbolic links as far as i know.

if you think you have found a bug, please describe what the actual vs expected behaviour is and post your settings.py and your directory structure. if you think something is unnecessarily complex or documentation is missing, please tell us so but be more specific :)

**Comment by karyon** [comment] 2016-07-31 11:41
unclear what the problem is, closing.

**Closed by karyon** 2016-07-31 11:41 UTC
