### ISSUE TITLE
SuspiciousFileOperation running compress

### ISSUE THREAD

**Issue by goetzk** [django-compressor/django-compressor#799] opened 2016-10-15 08:03 UTC
Hi,
I have had a look around and haven't found an obvious solution to this problem so thought I should raise an issue.

I added compressor to my INSTALLED_APPS and the following configuration

```
COMPRESS_ENABLED = True
STATICFILES_FINDERS += ('compressor.finders.CompressorFinder',)
```

In my template I loaded compress and wrapped a couple of css/js files from one template in what I believe to be the correct way

```
{% load compress %}

{% compress css %}
    <!-- Theme Global Style
=========================================================== -->
    <link href="{{ THEME_URL }}media/css/global-style.css" rel="stylesheet">
    <link rel="stylesheet" href="{{ THEME_URL }}media/assets/layerslider/css/layerslider.css" type="text/css">
    <!-- Bootstrap theme
=========================================================== -->

    <!-- navigation dropdowns
=========================================================== -->
    <link href="{{ THEME_URL }}media/css/meanmenu.css" rel="stylesheet">

    <!-- Custom styles for this template
=========================================================== -->
    <link href="{{ THEME_URL }}media/css/bootstrap-theme.css" rel="stylesheet">
{% endcompress %}
```

When I reload django and view my pages they are still using the same files as they had before i loaded compressor so obviously not working there.

When I run compress via manage.py I see the following error

```
root@tendenci-web:/srv/tendenci/website# python ./manage.py compress --force
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/dist-packages/compressor/management/commands/compress.py", line 291, in handle
    self.compress(sys.stdout, **options)
  File "/usr/local/lib/python2.7/dist-packages/compressor/management/commands/compress.py", line 173, in compress
    template = parser.parse(template_name)
  File "/usr/local/lib/python2.7/dist-packages/compressor/offline/django.py", line 97, in parse
    return get_template(template_name).template
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader.py", line 35, in get_template
    return engine.get_template(template_name, dirs)
  File "/usr/local/lib/python2.7/dist-packages/django/template/backends/django.py", line 30, in get_template
    return Template(self.engine.get_template(template_name, dirs))
  File "/usr/local/lib/python2.7/dist-packages/django/template/engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/usr/local/lib/python2.7/dist-packages/django/template/engine.py", line 141, in find_template
    source, display_name = loader(name, dirs)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loaders/base.py", line 13, in __call__
    return self.load_template(template_name, template_dirs)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loaders/cached.py", line 62, in load_template
    template, origin = self.find_template(template_name, template_dirs)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loaders/cached.py", line 41, in find_template
    template, display_name = loader(name, dirs)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loaders/base.py", line 13, in __call__
    return self.load_template(template_name, template_dirs)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loaders/base.py", line 17, in load_template
    template_name, template_dirs)
  File "/usr/local/lib/python2.7/dist-packages/tendenci/apps/theme/template_loaders.py", line 85, in load_template_source
    for filepath in self.get_template_sources(template_name, template_dirs):
  File "/usr/local/lib/python2.7/dist-packages/tendenci/apps/theme/template_loaders.py", line 72, in get_template_sources
    yield safe_join(template_path, template_name)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/_os.py", line 85, in safe_join
    'component ({})'.format(final_path, base_path))
django.core.exceptions.SuspiciousFileOperation: The joined path (/usr/local/lib/python2.7/dist-packages/tendenci/apps/jobs/templates/jobs/invoice_view_display.html) is located outside of the base path component (/srv/tendenci/website/themes/boomerang/templates)
```

Its obviously trying to operate on an application loaded in by my INSTALLED_APPS. Am I able to force compressor to only work on particular templates? Is there a way to operate on files outside the base path?
I'm hopeful there is a solution to this as compressor is looking like a really good solution.

thanks,

**Comment by karyon** [comment] 2016-10-31 13:43
have you been able to fix this in the meantime?

if not, could you post your settings.py? ideally everything if you can.

**Comment by goetzk** [comment] 2016-11-02 01:24
Information I see I missed in my first comment:
* So far I have only edited one template - the home page (i updated my post to include that)
* I'm using compress in a Tendenci install (https://github.com/tendenci/tendenci), the template i changed was https://github.com/tendenci/tendenci-project-template/blob/master/themes/boomerang/templates/homepage.html#L44 at L44 and L277

As an update:
I have not found a solution to the offline compression problem but can confirm that compress is working as expected with customer facing html being served using the generated cache files on the pages I've tested with so far.
Settings.py comes in two parts. First is identical to this bit provided by tendenci https://github.com/tendenci/tendenci-project-template/blob/master/conf/settings.py
Second is almost identical to https://github.com/tendenci/tendenci-project-template/blob/master/conf/local_settings.py but for the sake of easy access I've included it all below.

Its a test/disposable install , even so i've removed the keys/passwords below
```
# Method that pulls settings from the standard settings.py
# file so that you can append or override items.
def get_setting(setting):
    import settings
    return getattr(settings, setting)

SECRET_KEY=''
SITE_SETTINGS_KEY=''

MIDDLEWARE_CLASSES = get_setting('MIDDLEWARE_CLASSES')

# Enable HTML minification https://github.com/cobrateam/django-htmlmin/
# Remmber memcache is holding page content so restart that if this doesn't stick.
MIDDLEWARE_CLASSES += (
  'django.middleware.cache.UpdateCacheMiddleware',
  'htmlmin.middleware.HtmlMinifyMiddleware',
  'django.middleware.cache.FetchFromCacheMiddleware',
  'htmlmin.middleware.MarkRequestMiddleware',
)

INSTALLED_APPS = get_setting('INSTALLED_APPS')

INSTALLED_APPS += (
    'django.contrib.gis',
    'tendenci.apps.committees',
    'tendenci.apps.case_studies',
    'tendenci.apps.donations',
    'tendenci.apps.speakers',
    'tendenci.apps.staff',
    'tendenci.apps.studygroups',
    'tendenci.apps.videos',
    'tendenci.apps.testimonials',
    'tendenci.apps.social_services',
    # -- explorer block --
    'tendenci.apps.explorer_extensions',
    'explorer',
    # -- end of explorer block --
    'compressor',
    # --helpdesk --
    #'markdown_deux',
    #'bootstrapform',
    #'tendenci.apps.helpdesk',
    # -- end of helpdesk
)

USE_I18N = True
ALLOWED_HOSTS = ["*"]

SITE_MODE = 'prod'

ADMINS = ()

DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'NAME': 'tendenci',
        'HOST': '',
        'USER': '',
        'PASSWORD': '',
        'PORT': 5432,
        'autocommit': True,
        },
    'another': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': '',
        'HOST': '',
        'USER': '',
        'PASSWORD': '',
        'PORT':'3306',
        }
}


SSL_ENABLED = False
CELERY_IS_ACTIVE = False

# Local time zone for this installation. Choices can be found here:
# http://en.wikipedia.org/wiki/List_of_tz_zones_by_name
# although not all choices may be available on all operating systems.
# In a Windows environment this must be set to your system time zone.
TIME_ZONE = 'Australia/Hobart'

# -------------------------------------- #
# DEBUG OPTIONS
# -------------------------------------- #
SENTRY_DSN = ""
if SENTRY_DSN:
    INSTALLED_APPS += ('raven.contrib.django.raven_compat',)
    RAVEN_CONFIG = {
        'dsn': SENTRY_DSN,
}
# ---------------------------------------#
# PAYMENT GATEWAY
# ---------------------------------------#
# authorizenet, firstdata (the first two)
MERCHANT_LOGIN = ''
MERCHANT_TXN_KEY = ''
AUTHNET_MD5_HASH_VALUE = False

# paypalpayflowlink (currently US only unfortunately per PayPal)
PAYPAL_MERCHANT_LOGIN = ''
PAYFLOWLINK_PARTNER = 'PayPal'

# stripe
STRIPE_SECRET_KEY = ''
STRIPE_PUBLISHABLE_KEY = ''

# -------------------------------------- #
# EMAIL
# -------------------------------------- #
# remove or comment out this line once you have your email backend set up.
EMAIL_BACKEND = 'django.core.mail.backends.dummy.EmailBackend'

# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_USE_TLS = False
# EMAIL_HOST = None
# EMAIL_PORT = 25
# EMAIL_HOST_USER = None
# EMAIL_HOST_PASSWORD = None

#EMAIL_BACKEND = "django_ses.SESBackend"
# AWS_ACCESS_KEY_ID = ''
# AWS_SECRET_ACCESS_KEY = ''

DEFAULT_FROM_EMAIL = "no-reply@example.com"
SERVER_EMAIL = DEFAULT_FROM_EMAIL

# -------------------------------------- #
# CACHE
# -------------------------------------- #

SITE_CACHE_KEY = SECRET_KEY
CACHE_PRE_KEY = SITE_CACHE_KEY


CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.dummy.DummyCache',
    }
}# Local memcached requires memcached to be running locally.
MEMCACHED_ENABLED = True
if MEMCACHED_ENABLED:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.memcached.MemcachedCache',
            'LOCATION': "127.0.0.1:11211",
        }
    }
CACHES['default']['TIMEOUT'] = 60 * 60 * 24 * 30  # 30 days


# sql explorer only allows superuser
EXPLORER_PERMISSION_VIEW =  lambda u: u.is_superuser
EXPLORER_PERMISSION_CHANGE =  lambda u: u.is_superuser

# helpdesk
#HELPDESK_REDIRECT_TO_LOGIN_BY_DEFAULT = True

# debug mode
DEBUG = False
DEBUG_TOOLBAR = False

TEMPLATES = get_setting('TEMPLATES')
TEMPLATES[0]['OPTIONS']['debug'] = DEBUG
# Turn off the template caching
# TEMPLATES[0]['OPTIONS']['loaders'] = [
#                 'app_namespace.Loader',
#                 'tendenci.apps.theme.template_loaders.Loader',
#                 'django.template.loaders.filesystem.Loader',
#                 'django.template.loaders.app_directories.Loader',
#             ]

# Configuration for 'compress', c/o
# https://django-compressor.readthedocs.io/en/latest/quickstart/        
# Should already be true because debug is false, test
COMPRESS_ENABLED = True
STATICFILES_FINDERS = get_setting('STATICFILES_FINDERS')
STATICFILES_FINDERS += ('compressor.finders.CompressorFinder',)
COMPRESS_URL = '/'
COMPRESS_OUTPUT_DIR = '/static/CACHE/'
COMPRESS_ROOT = get_setting('PROJECT_ROOT')
# testing, didn't fix
TEMPLATES[0]['DIRS'] += ('/usr/local/lib/python2.7/dist-packages/tendenci/apps/',)

```

You will note the slightly odd COMPRESS_* options dance; its because tendenci contains files in multiple directories (e.g. media/ , themes/, static/) and files needing compression can appear in any of them.

I opened tendenci/issues/526 while investigating this because I was hoping the error was actually due to jobs.css being missing - i touched the file and the error continues so sadly that wasn't it.

thanks,

**Comment by karyon** [comment] 2016-11-02 19:31
well, tendenci seems to bring along their own template loaders... could you print out the `template_name` parameter in the `template = parser.parse(template_name)` line in `compress.py`? maybe that gives a hint where to look for the root cause. 

so yeah i can try giving you some remote assistance in debugging this, but i won't have time to reproduce your setup and test this by myself...

**Comment by goetzk** [comment] 2016-11-03 03:54
On 3/11/16 06:31, Johannes Linke wrote:
> well, tendenci seems to bring along their own template loaders... could
> you print out the |template_name| parameter in the |template =
> parser.parse(template_name)| line in |compress.py|? maybe that gives a
> hint where to look for the root cause.

Unfortunately it doesn't seem to provide anything:
```
root@tendenci-web:/srv/tendenci/website# python ./manage.py compress --force
/usr/local/lib/python2.7/dist-packages/tendenci/apps/jobs/templates/jobs/invoice_view_display.html
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File
"/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py",
line 354, in execute_from_command_line
    utility.execute()
[...]
  File "/usr/local/lib/python2.7/dist-packages/django/utils/_os.py",
line 85, in safe_join
    'component ({})'.format(final_path, base_path))
django.core.exceptions.SuspiciousFileOperation: The joined path
(/usr/local/lib/python2.7/dist-packages/tendenci/apps/jobs/templates/jobs/invoice_view_display.html)
is located outside of the base path component
(/srv/tendenci/website/themes/boomerang/templates)
```


> so yeah i can try giving you some remote assistance in debugging this,
> but i won't have time to reproduce your setup and test this by myself...

Certainly don't blame you there.

I've read online that sometimes the error is a red herring, caused by
incorrect error handling at another point in the backtrace. I'll try and
check all the errors through that stack and see if I can spot where it
might be but given the number of lines I'll have to chip away at it for
a while to come.

thanks,

**Comment by karyon** [comment] 2016-11-03 10:49
sorry if i was unclear, i meant something like a `print(template_name)` in front of the `template = parser.parse(template_name)` line :) that should print the names before the stacktrace shows up.

**Comment by karyon** [comment] 2016-11-23 19:47
have you found anything that might help?

**Comment by goetzk** [comment] 2016-11-29 00:04
Hi,
Sorry about the delay, I totally forgot I had this issue open.

I had another look today and in an effort to track it down added code to print out the first 10 templates plus the template being worked on

```
root@tendenci-web:/srv/tendenci/website# python ./manage.py compress --force
first ten templates:  ['/usr/local/lib/python2.7/dist-packages/tendenci/apps/jobs/templates/jobs/invoice_view_display.html', '/srv/tendenci/website/themes/creative/templates/dashboard/new.html', '/usr/local/lib/python2.7/dist-packages/tendenci/apps/events/templates/notification/event_deleted/full.html', '/usr/local/lib/python2.7/dist-packages/tendenci/apps/files/templates/files/top_nav.html', '/usr/local/lib/python2.7/dist-packages/tendenci/apps/base/static/codemirror/highlight.html', '/usr/local/lib/python2.7/dist-packages/tendenci/apps/user_groups/templates/user_groups/newsletter_unsubscribe.html', '/usr/local/lib/python2.7/dist-packages/tendenci/apps/social_services/templates/social_services/base.html', '/usr/local/lib/python2.7/dist-packages/tendenci/apps/navs/templates/navs/search.html', '/usr/local/lib/python2.7/dist-packages/tendenci/templates/theme_includes/image_edit_form.html', '/usr/local/lib/python2.7/dist-packages/tendenci/apps/payments/templates/payments/top_nav.html']
current template name: /usr/local/lib/python2.7/dist-packages/tendenci/apps/jobs/templates/jobs/invoice_view_display.html
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/dist-packages/compressor/management/commands/compress.py", line 295, in handle
    self.compress(sys.stdout, **options)
  File "/usr/local/lib/python2.7/dist-packages/compressor/management/commands/compress.py", line 175, in compress
    print('parsING template: %s') % parser.parse(template_name)
  File "/usr/local/lib/python2.7/dist-packages/compressor/offline/django.py", line 97, in parse
    return get_template(template_name).template
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader.py", line 35, in get_template
    return engine.get_template(template_name, dirs)
  File "/usr/local/lib/python2.7/dist-packages/django/template/backends/django.py", line 30, in get_template
    return Template(self.engine.get_template(template_name, dirs))
  File "/usr/local/lib/python2.7/dist-packages/django/template/engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/usr/local/lib/python2.7/dist-packages/django/template/engine.py", line 141, in find_template
    source, display_name = loader(name, dirs)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loaders/base.py", line 13, in __call__
    return self.load_template(template_name, template_dirs)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loaders/cached.py", line 62, in load_template
    template, origin = self.find_template(template_name, template_dirs)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loaders/cached.py", line 41, in find_template
    template, display_name = loader(name, dirs)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loaders/base.py", line 13, in __call__
    return self.load_template(template_name, template_dirs)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loaders/base.py", line 17, in load_template
    template_name, template_dirs)
  File "/usr/local/lib/python2.7/dist-packages/tendenci/apps/theme/template_loaders.py", line 85, in load_template_source
    for filepath in self.get_template_sources(template_name, template_dirs):
  File "/usr/local/lib/python2.7/dist-packages/tendenci/apps/theme/template_loaders.py", line 72, in get_template_sources
    yield safe_join(template_path, template_name)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/_os.py", line 85, in safe_join
    'component ({})'.format(final_path, base_path))
django.core.exceptions.SuspiciousFileOperation: The joined path (/usr/local/lib/python2.7/dist-packages/tendenci/apps/jobs/templates/jobs/invoice_view_display.html) is located outside of the base path component (/srv/tendenci/website/themes/boomerang/templates)
```

It didn't give me any direct leads so I decided to handle django.core.exceptions.SuspiciousFileOperation by continuing on failure rather than aborting.


```
from django.core.exceptions import SuspiciousFileOperation

[...]

#         print('first ten templates:  %s') % list(templates)[:10]
        for template_name in templates:
            try:
#                 print('current template name: ' + template_name)
#                 print('parsING template: %s') % parser.parse(template_name)
                template = parser.parse(template_name)
[...]
            except SuspiciousFileOperation:
# Temp disable output
#                 if verbosity > 0:
#                     log.write("SuspiciousFileOperation while trying to read "
#                               "template %s\n" % template_name)
                continue
```

That gives the following
```
root@tendenci-web:/srv/tendenci/website# python ./manage.py compress --force
Invalid template /srv/tendenci/website/themes/boomerang/templates/theme_includes/box.html: 'blocktrans' doesn't allow other block tags (seen u'spaceless') inside it
Found 'compress' tags in:
	/srv/tendenci/website/themes/boomerang/templates/homepage.html
CommandError: An error occurred during rendering /srv/tendenci/website/themes/boomerang/templates/homepage.html: 'media/css/global-style.css' isn't accessible via COMPRESS_URL ('/') and can't be compressed
Compressing... root@tendenci-web:/srv/tendenci/website# 
```

The block trans thing is an upstream issue so I am ignoring it for now, but when I checked where global-style.css was included I noticed the template does specify a path via THEME_URL.

```
{% compress css %}
    <!-- Theme Global Style
=========================================================== -->
    <link href="{{ THEME_URL }}media/css/global-style.css" rel="stylesheet">
...
{% endcompress %}
```

Which is defined in a custom context processor and included in Tendenci's TEMPLATES configuration

```
root@tendenci-web:/srv/tendenci/website# grep THEME_URL /usr/local/lib/python2.7/dist-packages/tendenci/apps/theme/context_processors.py
        contexts['THEME_URL'] = '%s/%s/%s/themes/%s/' % (settings.S3_ROOT_URL,
        contexts['THEME_URL'] = '/themes/' + theme + '/'
    contexts['LOCAL_THEME_URL'] = '/themes/' + theme + '/'
```

```
root@tendenci-web:/srv/tendenci/website# grep theme.context_process /usr/local/lib/python2.7/dist-packages/tendenci/settings.py
                'tendenci.apps.theme.context_processors.theme',
```

My thinking is that Tendenci is including its configuration but for some reason django-compressor doesn't have access to it.
I'm unsure if its the same problem as before or a new problem (i.e., i don't know if this would be related to the problem i was seeing at the start).

I should note this is only a problem when run via manage.py compress - compress is working great for pages served over http.

thanks,

**Comment by karyon** [comment] 2016-12-30 21:08
this might be a different problem, i think the THEME_URL might just not be defined. if you want to continue investigating this, check out the https://django-compressor.readthedocs.io/en/latest/settings/#django.conf.settings.COMPRESS_OFFLINE_CONTEXT setting and try to set it to the value that tendenci would use.

i investigated the original problem further. i think i have found the reason: tendenci actually expects that error to happen and attempts to catch it. unfortunately, django has changed the exception type in 1.8 and tendenci didn't update. i reported this (here)[https://github.com/tendenci/tendenci/issues/543]. so, now i'd wait for them to confirm that.

**Comment by karyon** [comment] 2017-01-02 22:43
they fixed it. i'll close this now, but i'd be glad to hear whether that fixed your issue!

**Closed by karyon** 2017-01-02 22:43 UTC
Labels: bug, needinfo
