### ISSUE TITLE
AttributeError at / 'Settings' object has no attribute 'COMPRESS_JS_COMPRESSOR'

### ISSUE THREAD

**Issue by serkansokmen** [django-compressor/django-compressor#333] opened 2012-11-03 14:26 UTC
i put COMPRESS_DEBUG_TOGGLE = 'blahblah' to my production settings, and now i got:

```
AttributeError at /
'Settings' object has no attribute 'COMPRESS_JS_COMPRESSOR'
```

and points me to this line in my template:

```
{% compress css %}
```

here is my production settings:

```
########## COMPRESSION CONFIGURATION
COMPRESS_ENABLED = True
# Default : the opposite of DEBUG

COMPRESS_OFFLINE = False
COMPRESS_STORAGE = DEFAULT_FILE_STORAGE
COMPRESS_CSS_FILTERS += [
    #'compressor.filters.cssmin.CSSMinFilter',
    'compressor.filters.template.TemplateFilter',
]
COMPRESS_JS_FILTERS += [
    #'compressor.filters.jsmin.JSMinFilter',
    'compressor.filters.template.TemplateFilter',
]

COMPRESS_DEBUG_TOGGLE = 'compressor'
########## END COMPRESSION CONFIGURATION
```

any suggestions?

(edit by @diox : original bug report info: https://github.com/jezdez/django_compressor/issues/173#issuecomment-10016037 )

**Comment by nferrari** [comment] 2015-03-20 16:00
Same problem here. My PR above resolves the problem for me but unfortunately does not pass Travis tests...

**Comment by jdunck** [comment] 2015-03-21 22:01
I believe I have found the root cause.

The issue is that loading settings can be reentrant, so that [LazySettings._setup](https://github.com/django/django/blob/465edf2bb2b6dd6158b198922dc0f185a15cc715/django/conf/__init__.py#L43) gets called twice.

This means that `AppConfMetaClass`'s holder refers to an object that doesn't end up being the `LazySettings._wrapped` object. `setattr(new_class._meta.holder, prefixed_name, value)` modifies an object that ends up not being the final settings.

Here is a log -- I modified Django to print entry and exit of LazySettings._setup, Settings.__init__ (including object ID), as well as AppConfMetaClass setting default and configured values.

You can set that Settings.__init__ imports the underlying settings module, which in my case imports waffle -- and waffle then refers to django.core.cache, which requires settings, starting the LazySettings._setup path again.  It loads successfully, but the `holder` object is not the object that eventually becomes LazySettings._wrapped.

Personally I think re-loading settings is an antipattern, but it's also pretty common, since loading settings loads INSTALLED_APPS models.py, which generally pulls in most of the codebase.  

I'm unclear on a clean fix here.  It seems like the "right" place to fix this would be Django, but that doesn't help any projects running on less than django+1.  It also seems likely that with 1.7's app loading rework, this may no longer be an issue.  (I'm on 1.6 presently, upgrading to 1.7 soon.)

I do wonder why compressor doesn't internally refer to AppConf rather than django.conf.settings.  

For now, I think AppConf should issue a warning when, after loading, it notices that django.conf.settings._wrapped is not the object that AppConf._meta.holder was.

Do you maintain AppConf, or is that effectively dead now that it's incorporated into 1.7?

````
(styleseat)mbp3:styleseat jdunck$ python manage.py shell
LazySettings._setup enter
  File "manage.py", line 9, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/jdunck/consulting/ss/venv/styleseat/lib/python2.7/site-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/Users/jdunck/consulting/ss/venv/styleseat/lib/python2.7/site-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/jdunck/consulting/ss/venv/styleseat/lib/python2.7/site-packages/django/core/management/__init__.py", line 261, in fetch_command
    commands = get_commands()
  File "/Users/jdunck/consulting/ss/venv/styleseat/lib/python2.7/site-packages/django/core/management/__init__.py", line 107, in get_commands
    apps = settings.INSTALLED_APPS
  File "/Users/jdunck/consulting/ss/venv/styleseat/lib/python2.7/site-packages/django/conf/__init__.py", line 58, in __getattr__
    self._setup(name)
  File "/Users/jdunck/consulting/ss/venv/styleseat/lib/python2.7/site-packages/django/conf/__init__.py", line 39, in _setup
    print "\n".join(traceback.format_stack())

Settings.__init__ enter 4419867728
LazySettings._setup enter
  File "manage.py", line 9, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/jdunck/consulting/ss/venv/styleseat/lib/python2.7/site-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/Users/jdunck/consulting/ss/venv/styleseat/lib/python2.7/site-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/jdunck/consulting/ss/venv/styleseat/lib/python2.7/site-packages/django/core/management/__init__.py", line 261, in fetch_command
    commands = get_commands()
  File "/Users/jdunck/consulting/ss/venv/styleseat/lib/python2.7/site-packages/django/core/management/__init__.py", line 107, in get_commands
    apps = settings.INSTALLED_APPS
  File "/Users/jdunck/consulting/ss/venv/styleseat/lib/python2.7/site-packages/django/conf/__init__.py", line 58, in __getattr__
    self._setup(name)
  File "/Users/jdunck/consulting/ss/venv/styleseat/lib/python2.7/site-packages/django/conf/__init__.py", line 52, in _setup
    self._wrapped = Settings(settings_module)
  File "/Users/jdunck/consulting/ss/venv/styleseat/lib/python2.7/site-packages/django/conf/__init__.py", line 133, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/Users/jdunck/consulting/ss/venv/styleseat/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/Users/jdunck/consulting/ss/code/styleseat/settings.py", line 1262, in <module>
    import waffle
  File "/Users/jdunck/consulting/ss/venv/styleseat/lib/python2.7/site-packages/waffle/__init__.py", line 6, in <module>
    from django.core.cache import cache
  File "/Users/jdunck/consulting/ss/venv/styleseat/lib/python2.7/site-packages/django/core/cache/__init__.py", line 69, in <module>
    if DEFAULT_CACHE_ALIAS not in settings.CACHES:
  File "/Users/jdunck/consulting/ss/venv/styleseat/lib/python2.7/site-packages/django/conf/__init__.py", line 58, in __getattr__
    self._setup(name)
  File "/Users/jdunck/consulting/ss/venv/styleseat/lib/python2.7/site-packages/django/conf/__init__.py", line 39, in _setup
    print "\n".join(traceback.format_stack())

Settings.__init__ enter 4432526480
Settings.__init__ exit
LazySettings._setup exit, _wrapped is 4432526480
default COMPRESS_CACHE_BACKEND = None
default COMPRESS_CACHE_KEY_FUNCTION = compressor.cache.simple_cachekey
...
applying AppConf to 4432526480
configured COMPRESS_CACHE_BACKEND = default
configured COMPRESS_CACHE_KEY_FUNCTION = compressor.cache.simple_cachekey
...
Settings.__init__ exit
LazySettings._setup exit, _wrapped is 4419867728
````

**Comment by nferrari** [comment] 2015-03-23 11:52
FYI, I encountered the problem with Django 1.8b1.

**Comment by jdunck** [comment] 2015-03-24 19:50
@nferrari Can you confirm that your LazySettings._setup is being called twice?

**Comment by wiel** [comment] 2015-03-25 01:46
I encountered a similar problem when I tried to use reverse in my settings file. first I got an error saying COMPRESS_DEBUG_TOGGLE did not exist. after adding that attribue, I got another error saying that COMPRESS_JS_COMPRESSOR did not exist. The problem went away when I used reverse_lazy

**Comment by carltongibson** [comment] 2015-03-25 08:05
If I'm following this right, if this is an issue (rather than a programming error — trying to _do things_ in settings at import time) then it's an issue with AppConf, and not compressor. 

The relevant location seems to be jezdez/django-appconf#13.

For sanity's sake, and to concentrate the chances of getting a resolution, we should close this and point all discussion there.

**Comment by carltongibson** [comment] 2015-09-20 20:10
Closing this as per my last comment. It's an AppConf issue. 

If anyone can help reproduce, please comment on be django-compressor/django-appconf#13

**Closed by carltongibson** 2015-09-20 20:10 UTC
