### ISSUE TITLE
manage.py compress fail 

### ISSUE THREAD

**Issue by dawalama** [django-compressor/django-compressor#709] opened 2015-12-16 20:03 UTC
> manage.py compress -v 3 
```
...
....
  File "/lib/python2.7/site-packages/compressor/management/commands/compress.py", line 158, in compress
    log.write("Considering paths:\n\t" + "\n\t".join(paths) + "\n")
TypeError: sequence item 0: expected string, EggOrigin found
```

**Comment by karyon** [comment] 2015-12-16 20:29
are you on django 1.9 and django-compressor 1.6 by any chance? because if i understand this correctly this shouldn't happen with django 1.8 or the current development of django-compressor.

**Comment by karyon** [comment] 2015-12-16 20:31
...pretty sure this is a duplicate of https://github.com/django-compressor/django-compressor/pull/695

**Comment by vladthedeployer** [comment] 2015-12-17 20:49
@karyon I am on django 1.9 / django-compressor 1.6. I am trying to upgrade my django base from 1.8.x to 1.9

**Comment by dawalama** [comment] 2015-12-17 20:52
@karyon correct. I am on django 1.9 / django-compressor 1.6. Trying to upgrade

**Comment by karyon** [comment] 2015-12-17 20:53
alright, cool! then it's definitely a duplicate and fixed in the current develop branch.

**Comment by diox** [comment] 2015-12-18 00:07
Yeah, that's a dupe of #695 then. Use django-compressor develop version while waiting for a new release, thanks.

**Closed by diox** 2015-12-18 00:07 UTC
