### ISSUE TITLE
Parse found templates with all offline contexts.

### ISSUE THREAD

**Issue by mrmachine** [django-compressor/django-compressor#857] opened 2017-05-26 02:19 UTC
We have many templates, some in 3rd party libraries, that use variables for base template names with `{% extends %}`. `django-compressor` currently just completely ignores these templates, as they generate a parse error when no context is available. Some of these templates have `[% compress %}` nodes, and some extend base templates that have compress nodes.

Is there any reason why we can't generate the list of templates containing `{% compress %}` nodes by parsing all found templates with all configured offline contexts? Just like we render all templates that are found to have `{% compress %}` nodes with all configured offline contexts?

I think I saw a comment in the code somewhere (can't find it now) saying that this was not supported because something needed to be refactored, but is there anything major that would prevent this from working?

**Comment by diox** [comment] 2017-05-26 10:50
Hi,

I think the refactor you're talking about was mentioned in #674, which have since be fixed in https://github.com/django-compressor/django-compressor/pull/758, which did add support for `{% extends variable %}`. Presumably something is still missing for your use-case ?

Please submit a failing testcase (or even better, a PR fixing the problem :) demonstrating the issue, anything involving offline compression is a complex topic and it's difficult to follow without looking at a concrete example.

**Comment by karyon** [comment] 2017-06-15 16:40
ping @mrmachine :)

**Comment by mrmachine** [comment] 2017-06-16 10:28
Sorry, we implemented a work-around by adding a new `django-compressor.html` template to our project which is not used anywhere, but which includes identical `{% compress %}` nodes that were being missed from templates that use a variable argument to `{% extends %}`.

I think I did try the latest version of `django-compressor` and still couldn't get our actual templates, but I'll have try to have another go at reproducing this.

**Comment by karyon** [comment] 2017-08-22 20:03
#758 even included a test covering this specific case: https://github.com/django-compressor/django-compressor/pull/758/files#diff-4634918cf78d3b83c1bf0c2ff681d283R440. i'll assume this is fixed, but if you would reproduce that with a current version of compressor, i can of course re-open this issue.

**Closed by karyon** 2017-08-22 20:03 UTC
Labels: needinfo
