### ISSUE TITLE
compress merge own test templates to production code

### ISSUE THREAD

**Issue by ondrejsika** [django-compressor/django-compressor#696] opened 2015-11-22 18:58 UTC
Hi, I have a problem. Compress command fails with:

```
CommandError: An error occured during rendering /home/projects/pool/web-pool/.env/lib/python2.7/site-packages/compressor/tests/test_templates/test_static_templatetag/test_compressor_offline.html: 'js/one.js' could not be found in the COMPRESS_ROOT '/home/projects/pool/web-pool/static/static' or with staticfiles.
```

When I add `js/one.js` to assets, it works properly.

Thanks, Ondrej

**Comment by diox** [comment] 2015-11-23 00:03
That's weird. More info is needed, what are your settings ?

**Comment by ondrejsika** [comment] 2015-11-23 10:00
Here is key part of my settings.py

```
DEBUG = False
COMPRESS_ENABLED = True
COMPRESS_OFFLINE = True

TEMPLATE_CONTEXT_PROCESSORS = (
    "django.contrib.auth.context_processors.auth",
    "django.core.context_processors.debug",
    "django.core.context_processors.i18n",
    "django.core.context_processors.media",
    "django.core.context_processors.static",
    "django.core.context_processors.tz",
    "django.contrib.messages.context_processors.messages",
    'django.core.context_processors.request',
    'web.context_processors.main',

    # CMS
    'sekizai.context_processors.sekizai',
    'django.core.context_processors.static',
    'cms.context_processors.cms_settings',
)

STATICFILES_FINDERS = (
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    'django.contrib.staticfiles.finders.DefaultStorageFinder',
    'compressor.finders.CompressorFinder',
)
COMPRESS_PRECOMPILERS = (
    ('text/coffeescript', 'coffee --compile --stdio'),
    ('text/x-scss', 'django_libsass.SassCompiler'),
)

STATIC_ROOT = os.path.join(BASE_DIR, 'static', 'static')
MEDIA_ROOT = os.path.join(BASE_DIR, 'static', 'static', 'uploads')
```

**Comment by karyon** [comment] 2016-04-24 08:40
did you find the cause in the meantime? if not, could you provide the full settings.py? i can't reproduce this even when copying all the parts you posted.

**Comment by karyon** [comment] 2016-06-01 20:22
not enough information, closing.

**Closed by karyon** 2016-06-01 20:22 UTC
Labels: bug

**Comment by kubijo** [comment] 2017-08-11 13:57
Hi.

I've been looking into this again and have been able to trace the issue to our misconfiguration of django's template finder; so if anyone has similar issue, here's the solution

The issues was really that compress tried to process templates which it weren't supposed to and so here is the config that was causing the problems (mind the `BASE_DIR` included in `DIRS`)

```python
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR, 'templates'],
        'APP_DIRS': True,
    }  
```

Cheers!
