### ISSUE TITLE
Please, add custom attributes to css and js.

### ISSUE THREAD

**Issue by narnikgamarnikus** [django-compressor/django-compressor#859] opened 2017-05-30 07:46 UTC
In my case, I needed to add a custom attribute, not just an async or defer.

By example, I needed to add `data-turbolinks-eval=false`.

And at this stage, this can not be done, except add to the sources code.

You just need to take a dict from the `settings.py` file, where the key is the attribute, and the meaning is what you need to specify, whether True or False.

But sometimes, it is necessary to specify some numerical value, for this, too, it is not worth neglecting.

**Comment by karyon** [comment] 2017-05-30 07:52
duplicate of #690 as far as i can see.

**Closed by karyon** 2017-05-30 07:52 UTC
