### ISSUE TITLE
Cannot install on Windows 

### ISSUE THREAD

**Issue by PunchyRascal** [django-compressor/django-compressor#945] opened 2019-06-21 12:56 UTC
While installing on Windows, rcssmin issues this error:

```
Collecting django-compressor
  Using cached https://files.pythonhosted.org/packages/43/e2/50e21afd7e13b522f7d1a29cf0a6dd65e19835950dce3be3c5928e668846/django_compressor-2.3-py2.py3-none-any.whl
Requirement already satisfied: rjsmin==1.1.0 in c:\users\x\.virtualenvs\xxx\lib\site-packages (from django-compressor) (1.1.0)
Requirement already satisfied: django-appconf>=1.0 in c:\users\x\.virtualenvs\xxx\lib\site-packages (from django-compressor) (1.0.3)
Collecting rcssmin==1.0.6 (from django-compressor)
  Using cached https://files.pythonhosted.org/packages/e2/5f/852be8aa80d1c24de9b030cdb6532bc7e7a1c8461554f6edbe14335ba890/rcssmin-1.0.6.tar.gz
Requirement already satisfied: django in c:\users\x\.virtualenvs\xxx\lib\site-packages (from django-appconf>=1.0->django-compressor) (2.2.1)
Requirement already satisfied: six in c:\users\x\.virtualenvs\xxx\lib\site-packages (from django-appconf>=1.0->django-compressor) (1.12.0)
Requirement already satisfied: pytz in c:\users\x\.virtualenvs\xxx\lib\site-packages (from django->django-appconf>=1.0->django-compressor) (2019.1)
Requirement already satisfied: sqlparse in c:\users\x\.virtualenvs\xxx\lib\site-packages (from django->django-appconf>=1.0->django-compressor) (0.3.0)
Building wheels for collected packages: rcssmin
  Running setup.py bdist_wheel for rcssmin: started
  Running setup.py bdist_wheel for rcssmin: finished with status 'error'
  Complete output from command C:\Users\x\.virtualenvs\xxx\Scripts\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\x\\AppData\\Local\\Temp\\pycharm-packaging\\rcssmin\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d C:\Users\FRANTI~1\AppData\Local\Temp\pip-wheel-1_04sw7b --python-tag cp37:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win32-3.7
  copying .\rcssmin.py -> build\lib.win32-3.7
  warning: build_py: byte-compiling is disabled, skipping.
  
  running build_ext
  building '_rcssmin' extension
  creating build\temp.win32-3.7
  creating build\temp.win32-3.7\Release
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -DEXT_MODULE=_rcssmin -UEXT_PACKAGE -I_setup/include -IC:\Users\x\AppData\Local\Programs\Python\Python37-32\include -IC:\Users\x\AppData\Local\Programs\Python\Python37-32\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\winrt" /Tcrcssmin.c /Fobuild\temp.win32-3.7\Release\rcssmin.obj
  rcssmin.c
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\link.exe /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:C:\Users\x\AppData\Local\Programs\Python\Python37-32\Libs /LIBPATH:C:\Users\x\.virtualenvs\xxx\libs /LIBPATH:C:\Users\x\.virtualenvs\xxx\PCbuild\win32 "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\LIB" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.17134.0\ucrt\x86" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.17134.0\um\x86" /EXPORT:PyInit__rcssmin build\temp.win32-3.7\Release\rcssmin.obj /OUT:build\lib.win32-3.7\_rcssmin.cp37-win32.pyd /IMPLIB:build\temp.win32-3.7\Release\_rcssmin.cp37-win32.lib
     Creating library build\temp.win32-3.7\Release\_rcssmin.cp37-win32.lib and object build\temp.win32-3.7\Release\_rcssmin.cp37-win32.exp
  Generating code
  Finished generating code
  LINK : fatal error LNK1158: cannot run 'rc.exe'
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\link.exe' failed with exit status 1158
  
  ----------------------------------------
  Running setup.py clean for rcssmin
Failed to build rcssmin
Installing collected packages: rcssmin, django-compressor
  Running setup.py install for rcssmin: started
    Running setup.py install for rcssmin: finished with status 'error'
    Complete output from command C:\Users\x\.virtualenvs\xxx\Scripts\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\x\\AppData\\Local\\Temp\\pycharm-packaging\\rcssmin\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\FRANTI~1\AppData\Local\Temp\pip-record-uhtwrq9k\install-record.txt --single-version-externally-managed --compile --install-headers C:\Users\x\.virtualenvs\xxx\include\site\python3.7\rcssmin:
    running install
    running build
    running build_py
    creating build
    creating build\lib.win32-3.7
    copying .\rcssmin.py -> build\lib.win32-3.7
    warning: build_py: byte-compiling is disabled, skipping.
    
    running build_ext
    building '_rcssmin' extension
    creating build\temp.win32-3.7
    creating build\temp.win32-3.7\Release
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -DEXT_MODULE=_rcssmin -UEXT_PACKAGE -I_setup/include -IC:\Users\x\AppData\Local\Programs\Python\Python37-32\include -IC:\Users\x\AppData\Local\Programs\Python\Python37-32\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\winrt" /Tcrcssmin.c /Fobuild\temp.win32-3.7\Release\rcssmin.obj
    rcssmin.c
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\link.exe /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:C:\Users\x\AppData\Local\Programs\Python\Python37-32\Libs /LIBPATH:C:\Users\x\.virtualenvs\xxx\libs /LIBPATH:C:\Users\x\.virtualenvs\xxx\PCbuild\win32 "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\LIB" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.17134.0\ucrt\x86" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.17134.0\um\x86" /EXPORT:PyInit__rcssmin build\temp.win32-3.7\Release\rcssmin.obj /OUT:build\lib.win32-3.7\_rcssmin.cp37-win32.pyd /IMPLIB:build\temp.win32-3.7\Release\_rcssmin.cp37-win32.lib
       Creating library build\temp.win32-3.7\Release\_rcssmin.cp37-win32.lib and object build\temp.win32-3.7\Release\_rcssmin.cp37-win32.exp
    Generating code
    Finished generating code
    LINK : fatal error LNK1158: cannot run 'rc.exe'
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\link.exe' failed with exit status 1158
    
    ----------------------------------------

  Failed building wheel for rcssmin
Command "C:\Users\x\.virtualenvs\xxx\Scripts\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\x\\AppData\\Local\\Temp\\pycharm-packaging\\rcssmin\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\FRANTI~1\AppData\Local\Temp\pip-record-uhtwrq9k\install-record.txt --single-version-externally-managed --compile --install-headers C:\Users\x\.virtualenvs\xxx\include\site\python3.7\rcssmin" failed with error code 1 in C:\Users\x\AppData\Local\Temp\pycharm-packaging\rcssmin\
You are using pip version 18.1, however version 19.1.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

```

**Comment by karyon** [comment] 2019-12-23 22:16
dupe of #807.

**Closed by karyon** 2019-12-23 22:16 UTC
