### ISSUE TITLE
Django 5.1 compatibility

### ISSUE THREAD

**Issue by nijel** [django-compressor/django-compressor#1244] opened 2024-05-23 06:30 UTC
Django 5.1 (currently alpha) removes `django.core.files.storage.get_storage_class()` what makes django-compressor fail:

```pytb
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/compressor/finders.py", line 2, in <module>
    from compressor.storage import CompressorFileStorage
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/compressor/storage.py", line 7, in <module>
    from django.core.files.storage import FileSystemStorage, get_storage_class
ImportError: cannot import name 'get_storage_class' from 'django.core.files.storage' (/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/django/core/files/storage/__init__.py)
```

**Comment by carltongibson** [comment] 2024-05-23 06:51
Hi @nijel yes, duplicate of #1187. That's pinned, but I'll adjust the title to mention 5.1 explicitly. 

We need to adjust how we reference the storages. There are a couple of PRs pointing in that direction, but we need to sit down and decide the pattern. 

My current thinking is that we need to add a `COMPRESS_STORAGE_ALIAS` setting, and then have compressor use that if defined, or add an entry using `COMPRESS_STORAGE` if not, probably at the moment of populating the AppRegistry, i.e. when `INSTALLED_APPS` is processed. 

It's on my radar to address this (if still pending) after DjangoCon Europe, so in the next few weeks. 

(Closing as duplicate.)

**Closed as not planned by carltongibson** 2024-05-23 06:51 UTC
