### ISSUE TITLE
Problem when COMPRESS_ENABLED is False

### ISSUE THREAD

**Issue by wzrd-clss** [django-compressor/django-compressor#646] opened 2015-08-20 06:42 UTC
On release 1.4 I have this issue where some of the content within some javascript files is missing when COMPRESS_ENABLED = False. When I rename the file, the problem seems to go away. What could be causing this issue?
#163 sounds like a similar issue

**Comment by diox** [comment] 2015-09-25 16:18
Need more info, what content is missing, what do the files/templates you are dealing with look like ?

**Comment by wzrd-clss** [comment] 2015-09-26 03:27
the first gist below is the original file. the second gist is the result of disabling compressor. starting from line 198 of the original file, three functions are missing. buttonEventAddToBasket, submitBasketMiniForm and submitFormMiniSuccess. the problem is also occurring in release 1.5 for me.

https://gist.github.com/wzrd-clss/57337f4d58a624d89e67
https://gist.github.com/wzrd-clss/ad345a3b909cdddf8a2e

this is a snippet of compressor's settings in settings.py
```python
BASE_DIR = os.path.dirname(os.path.dirname(__file__))
location = lambda x: os.path.join(BASE_DIR, x)
STATIC_ROOT = location('static')
STATIC_URL = '/static/'
COMPRESS_URL = STATIC_URL
COMPRESS_ROOT = STATIC_ROOT
COMPRESS_OFFLINE= False
COMPRESS_ENABLED= False
COMPRESS_PARSER = 'compressor.parser.HtmlParser' 
```

this is a snippet of the template that imports the file in the gist above. the file in the gist is called ui.js
```html
{% block scripts %}
    {% compress js %}
    <script src="{% static "home/js/jquery/jquery-1.9.1.min.js" %}"></script>
    <script src="{% static "home/js/jquery.placeholder.min.js" %}"></script>
    <!-- Twitter Bootstrap -->
    <script type="text/javascript" src="{% static "home/js/bootstrap/bootstrap.min.js" %}"></script>
    <!-- home -->
    <script src="{% static "home/js/home/ui.js" %}" type="text/javascript" charset="utf-8"></script>

    {% endcompress %}
{% endblock %}
```

**Comment by karyon** [comment] 2015-12-07 20:42
there's some other stuff missing, e.g. some lines in the init function, or the option dict got smaller. to me it looks like an older version of the file. could it be it's taking the file from a different location depending on whether compression is enabled? @wzrd-clss, do you still have this setup and can you check that?

**Comment by wzrd-clss** [comment] 2015-12-09 05:06
@karyon yes I still have this setup. The file seems to be the right one.
with COMPRESS_ENABLED= False
home/js/home/ui.js
COMPRESS_ENABLED= True
/static/CACHE/js/d92856c6c377.js

**Comment by karyon** [comment] 2015-12-09 08:56
@wzrd-clss just to be clear, when `COMPRESS_ENABLED = False`, the html that your browser gets points to ̀home/js/home/ui.js`, and the file content that the browser gets does not match the file contents on disk?

**Comment by wzrd-clss** [comment] 2015-12-09 12:32
@karyon yes, thats right

**Comment by karyon** [comment] 2015-12-16 18:28
i had a look at the code and in templatetags/compress.py, render_compressed() it should, as compress is disabled and no precompilers are set, return with the original content. so, i have no idea what is going on there.

@wzrd-clss would be cool if you could debug this. if you need any help with that, let me know. otherwise, i don't know how we should fix this.

**Comment by karyon** [comment] 2016-10-31 14:25
@wzrd-clss although it's been a year, one last ping. have you been able to find a solution?

**Comment by wzrd-clss** [comment] 2016-10-31 15:16
@karyon i did not find a solution. its not an issue for me anymore since i have moved on to other projects

**Comment by karyon** [comment] 2016-10-31 16:18
alright, i'll close this as it doesn't seem to be happening to anyone else and we'll probably never find the cause for it.

**Closed by karyon** 2016-10-31 16:18 UTC
Labels: needinfo
