### ISSUE TITLE
Uncaught SyntaxError: missing ) after argument list

### ISSUE THREAD

**Issue by baltechies** [django-compressor/django-compressor#901] opened 2018-03-19 07:01 UTC
I am facing error in browser console "Uncaught SyntaxError: missing ) after argument list".
Same code is working fine in local machine, but on testing server its throwing the error. 
Not sure where is the issue. 

Django version : 1.11.9
Python version: 2.7.12

**Comment by karyon** [comment] 2018-03-19 13:18
Well, without any further information there is little i can do. What are your settings? Your templates? Please figure out what's the difference between your local machine and the test server that causes this problem to appear.

**Comment by baltechies** [comment] 2018-03-19 14:10
simple settings
STATICFILES_FINDERS = (
    'compressor.finders.CompressorFinder',
)

INSTALLED_APPs=(
.....
'compressor',
....
)

if DEBUG:
    COMPRESS_ENABLED = True


We are using html files in template. basically we are using angular at frontend. Files compression is working fine. but compressed files throwing the error at testing server but its working well at local.

Difference between local machine and test server
Local machine has mac os, python version is 2.7.10 and Django version : 1.11.9
Test server has elastic beanstalk aws server, python version is 2.7.12 and Django version : 1.11.9

**Comment by karyon** [comment] 2018-03-24 16:34
have you found out anything in the meantime?

if it works on the server, but does not work locally, there has to be some difference between the setups that causes this problem, e.g. installed packages versions and your settings. figuring out what difference is the one that causes the problem is something you have to do by yourself, there is little i can do to help you with that.

**Comment by baltechies** [comment] 2018-03-24 16:56
No, I did not find anything to resolve this.

Its working fine locally, but causes the problem on server.  Packages version and settings are same. We are using composer to manage package versions. 

Also is there any setting to merge the files into single file but do not compress/minify the files?

**Comment by karyon** [comment] 2018-03-24 16:58
yes. https://django-compressor.readthedocs.io/en/latest/settings/#django.conf.settings.COMPRESS_JS_FILTERS

**Comment by baltechies** [comment] 2018-03-24 17:16
Thank you!
I will check it by set compressor.filters.jsmin.JSMinFilter value to false. 
And will let you know if its still throwing the error.

**Comment by baltechies** [comment] 2018-03-27 10:39
Hi,
I had set COMPRESS_JS_FILTERS = [], then its working fine on staging server as well. Its seems that compression is creating the issue.

**Comment by karyon** [comment] 2018-04-02 18:23
i would probably blame the js minifier. you can test that by setting a different one.

in any case, closing because not enough information and most likely not django-compressors fault. if you have any news, feel free to post them.

**Closed by karyon** 2018-04-02 18:23 UTC
