### ISSUE TITLE
It takes a long time to load pages that compile SASS

### ISSUE THREAD

**Issue by epicserve** [django-compressor/django-compressor#508] opened 2014-04-23 01:29 UTC
It's taking ~1.0s to load pages that compile SASS. If I comment out the following in the template it takes ~70ms to load the page.

```html
{% compress css %}
<link type="text/x-scss" rel="stylesheet" href="{{ STATIC_URL }}scss/base.scss" charset="utf-8">
{% endcompress %}
```
I've setup my django-base-site so anyone that wants to look into this can replicate what I'm talking about. To install the base site just follow the [setup docs](https://github.com/epicserve/django-base-site/tree/compressor-sass-example/docs/usage-and-setup.rst).

The base template is located [here](https://github.com/epicserve/django-base-site/tree/compressor-sass-example/templates/base/base.html) and the settings are located [here](https://github.com/epicserve/django-base-site/tree/compressor-sass-example/config/settings/base.py).

**Comment by karyon** [comment] 2015-09-21 14:00
the base.scss includes bootstrap. so, when loading that page, bootstrap gets compiled. i think 1s is pretty good for that :) in any case, i'd assume any speedyness or slowness is caused by the compiler, not django-compressor.

by now there is the setting COMPRESS_CACHEABLE_PRECOMPILERS, where you can tell compressor to not compile files of that precompiler if they were not changed. have a look at https://django-compressor.readthedocs.org/en/latest/settings/#django.conf.settings.COMPRESS_CACHEABLE_PRECOMPILERS.

voting for closing this :)

**Closed** 2015-09-21 14:02 UTC
