### ISSUE TITLE
Not compatible with django-components

### ISSUE THREAD

**Issue by spapas** [django-compressor/django-compressor#1201] opened 2023-07-27 11:35 UTC
When I try to run `python manage.py compress` on a project that uses django-components (https://github.com/EmilStenstrom/django-components/) I get the following error:

```
  File "C:\progr\py3\ehcg\venv\lib\site-packages\compressor\offline\django.py", line 84, in remove_block_nodes
    setattr(node, attr, sub_nodelist)
AttributeError: can't set attribute 'nodelist'
```

After some debugging it seems that it can't handle the component_block for example like this: 

```
      {% component_block "card" "Εμφάνιση στοιχείων" color="" header_color="bg-info" header_text_color="text-light" %}
        {% fill "body" %}
          {% for p in ac.object_lists %}
            <a class='btn btn-info mt-1' href='{% url "object-list-detail" p.0 %}'>{{ p.1 }}</a>
          {% endfor %}
        {% endfill %}
      {% endcomponent_block %}
```

**Comment by carltongibson** [comment] 2023-07-27 13:34
Yeah... looking at the code it's because nodelist is a property there. (Quickest glance so that may not be 100% the issue, but ...)

I'd say this'll be easier to debug over there.

**Comment by spapas** [comment] 2023-07-27 14:33
@carltongibson cool I'll open it there also and close it from both places when it gets fixed thank you!

**Comment by carltongibson** [comment] 2023-07-27 14:41
Yeah... Not being able to set the nodelist looks like a problem, but clearly not one we can solve over here, so likely this'll be invalid from compressor's perspective.

**Comment by EmilStenstrom** [comment] 2023-08-07 21:46
@carltongibson Thanks for debugging this for us! We'll see if someone takes up the torch and fixes it over at django-components.

**Comment by housUnus** [comment] 2023-08-14 21:46
I ran into the same problem, the issue is when I modify a certain CSS file in whatever place it works fine, the CSS CACHE is generated automatically, so the generation of cache is working fine except with the compress command.

**Comment by spapas** [comment] 2024-01-03 07:46
Hello friends and happy new year. Because I'm not sure this will ever be fixed, I've added the following small patch on my repo:

https://github.com/django-compressor/django-compressor/compare/develop...spapas:django-compressor:develop

Would you consider adding this also on the official django-compressor (maybe with a little more explanation when the error happens) so I'd be able to use it without the need to use my fork from github? 

Thank you

**Comment by spapas** [comment] 2024-01-03 07:46
@carltongibson probably you're the one to decide so I'm pinging you!

**Comment by carltongibson** [comment] 2024-01-03 08:03
Hey @spapas — Happy New Year! 🥳

> Would you consider adding this also on the official django-compressor (maybe with a little more explanation when the error happens)

Yes! 

If you could recreate it in a test case, that would be amazing! 🤩

> ... maybe with a little more explanation ...

Is catching the error enough, or are the generated files affected?

> ... so the generation of cache is working fine except with the compress command.

So exactly what's going on there? Is it just a docs issue... — but lots of folks rely on offline compression… 🤔

>  I'm not sure this will ever be fixed

If someone (you 😅) can dig into, very happy to have it fixed, but it's not high on my list currently… (Django components is on my radar but didn't get to play with it yet.)

**Comment by EmilStenstrom** [comment] 2024-01-19 22:03
@dylanjcastillo managed to solve this on the django-components side, so feel free to close this one!

**Comment by carltongibson** [comment] 2024-01-20 06:30
Thanks @EmilStenstrom 🎁

**Closed as not planned** 2024-01-20 06:30 UTC
