### ISSUE TITLE
Uncaught SyntaxError: Unexpected string when compressing via compressor

### ISSUE THREAD

**Issue by pythdasch** [django-compressor/django-compressor#844] opened 2017-04-20 12:19 UTC
Hi everyone,

I do an offline compression and when I deploy it there is a : Uncaught SyntaxError: Unexpected string in my JS.

But I don't understand why, the js looks fine, here are the settings and the js file:

```
__all__ = ["COMPRESS_OFFLINE", "COMPRESS_OFFLINE_CONTEXT"]


def get_setting_lazy(setting_name):
    """
    Returns a function that returns the value of the setting_name.
    """
    def inner():
        from django.conf import settings
        return getattr(settings, setting_name)
    return inner


def get_mezzanine_settings():
    """
    Returns the value of the mezzanine.conf.context_processors.settings context
    processor. Context processors usually can only be run during a request, but
    luckily, mezzanine ignores the request parameter, so we don't have to worry
    about it.
    """
    from mezzanine.conf.context_processors import settings
    return settings()['settings']


def get_site():
    """
    Returns the Widgy site. """    # if not using widgy_mezzanine, just import your widgy site directly here.
    from settings import WIDGY_MEZZANINE_SITE
    from widgy.utils import fancy_import
    return fancy_import(WIDGY_MEZZANINE_SITE)


# Kick compressor into OFFLINE mode
COMPRESS_OFFLINE = True

# This is the context that is provided when compressing assets offline.
COMPRESS_OFFLINE_CONTEXT = {
    'STATIC_URL': get_setting_lazy('STATIC_URL'),

    # some mezzanine templates require the settings.
    'settings': get_mezzanine_settings,
    'request': type('Request', (), {'META': {}}),

    # widgy_field.html needs the site
    'site': get_site,
}


COMPRESS_OFFLINE = True


COMPRESS_ENABLED = True
```

and the JS file (I already tried to remove it and the error will just jump to another file : 

```
    function BuildDiscussion(object) {
        html = "<li class='shift-bot-1x'>";
        html += "<p>" + object.phrase + "</p>";
        html += "<div class='row text-center'>";
        html += "<a class='col-sm-6 like-discussion' href='" + object.url + "' data-discussion='" + object.id + "' data-like='0'>0 like</a>";
        html += "<a class='col-sm-6 like-discussion' href='" + object.url + "' data-discussion='" + object.id + "' data-like='1'>0 dislike</a>";
        html += "</div>";
        return html
    }
```

And finally my compress tag : 
```
{% compress js %}
<script src="{% static 'js/main.js' %}"></script>
<script src="{% static 'js/global.js' %}"></script>
<script src="{% static 'js/components/ajax-utils.js' %}"></script>
<script src="{% static 'js/components/auth.js' %}"></script>
<script src="{% static 'js/components/selecttextevent.js' %}"></script>
<script src="{% static 'js/components/smart_select.js' %}"></script>
<script src="{% static 'js/components/utils.js' %}"></script>
<script src="{% static 'js/components/map.js' %}"></script>
<script src="{% static 'js/components/search-city.js' %}"></script>
<script src="{% static 'js/components/words.js' %}"></script>
<script src="{% static 'js/sections/index.js' %}"></script>
<script src="{% static 'js/sections/profile.js' %}"></script>
<script src="{% static 'js/sections/landing.js' %}"></script>
<script src="{% static 'js/sections/socials.js' %}"></script>
<script src="{% static 'js/sections/publications.js' %}"></script>
<script src="{% static 'js/sections/actions.js' %}"></script>
<script src="{% static 'js/sections/projects.js' %}"></script>
<script src="{% static 'js/sections/project.js' %}"></script>
<script src="{% static 'js/sections/people.js' %}"></script>
{% endcompress %}
```

If anyone has a clue what's happening would be so nice ! I'm struggling with this error.

I use django compressor + whitenoise for my staticfiles under dokku

**Comment by karyon** [comment] 2017-05-11 15:44
unfortunately i don't know what the problem is either. without a reduced test case any attempt at understanding this will be pure guesswork :)

**Comment by pythdasch** [comment] 2017-05-16 13:17
I just don't use compressor anymore, since it was too mysterious

**Comment by pythdasch** [comment] 2017-05-16 13:17
I think it's due to yuglify options apparently. So now I use my own yuglify functions to handle all of this

**Comment by karyon** [comment] 2017-05-16 15:04
sorry to hear that. since it seems unlikely to be fixed this way, i'll close this issue.

**Closed by karyon** 2017-05-16 15:04 UTC
Labels: needinfo
