### ISSUE TITLE
Deploying to heroku memacahced error

### ISSUE THREAD

**Issue by vladimirnani** [django-compressor/django-compressor#793] opened 2016-08-19 22:40 UTC
When i am deploying to heroku i receive dozens of following errors:

```
MemcachedError: error 3 from memcached_get(:1:django_compressor.mtime.8fb53): (0x1be5490) 
CONNECTION FAILURE(Connection refused),  host: localhost:11211 -> libmemcached/connect.cc:156

ConnectionError
error 3 from memcached_get(:1:django_compressor.mtime.8fb53): (0x1be5490)
 CONNECTION FAILURE(Connection refused),  host: localhost:11211 -> libmemcached/connect.cc:156
```

I think it happens when it tries to collect static during deploy. 

Any thoughts on how can i prevent these errors. Thanks.

**Comment by karyon** [comment] 2016-09-05 18:31
as far as i understand, this is fixed with the workaround in #363, is that correct?

**Comment by vladimirnani** [comment] 2016-09-05 18:42
Yes

**Comment by karyon** [comment] 2016-09-05 18:46
duplicate of #363.

**Closed by karyon** 2016-09-05 18:46 UTC
