### ISSUE TITLE
Subresource Integrity (SRI) support

### ISSUE THREAD

**Issue by sikmir** [django-compressor/django-compressor#892] opened 2017-12-11 09:10 UTC
### Steps to reproduce
Template:
```html
{% compress js %}
<script src="jquery/dist/jquery.min.js" integrity="sha384-xBuQ/xzmlsLoJpyjoggmTEz8OWUFM0/RC5BsqQBDX2v5cMvDHcMakNTNrHIW2I5f" crossorigin="anonymous"></script>
<script src="bootstrap/dist/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
{% endcompress %}
```

### Actual behaviour
Output:
```html
<script type="text/javascript" src="js/90f56f23d532.js"></script>
```

### Expected behaviour
Output:
```html
<script type="text/javascript" src="js/90f56f23d532.js" integrity="sha384-pQOX/9TG7mK8Y5N9ORIWw/+kJh5f/pp4qIdYOncsnzEB4rF0KqYcf69Pk5Tb5U0M" crossorigin="anonymous"></script>
```
Where
```bash
$ cat js/90f56f23d532.js | openssl dgst -sha384 -binary | openssl base64 -A
pQOX/9TG7mK8Y5N9ORIWw/+kJh5f/pp4qIdYOncsnzEB4rF0KqYcf69Pk5Tb5U0M
```

### Links
 * [Subresource Integrity (W3C Recommendation 23 June 2016)](https://www.w3.org/TR/SRI)

### Configuration
Compressor version: 2.2

**Comment by karyon** [comment] 2017-12-17 20:12
duplicate of #661.

**Comment by karyon** [comment] 2017-12-17 20:13
...provided you'd be fine with django-compressor computing the checksums by itself ;)

**Closed by karyon** 2017-12-17 20:12 UTC
